- assets/css/stlye.css
- index.html
I did some things to HTML. Added banner, description, search bar and CSS
> added html structure banner, description, search bar, and css

- assets/css/stlye.css
- index.html
Added tailwind to text and styling to CSS
> added tailwind css to the header and div tags, added styling to CSS

- assets/css/stlye.css
- index.html
> added tailwind to HTML and styling to CSS

- index.html
> HTML fixed

- assets/javascript/script.js
> fixed api key

- assets/javascript/script.js
- index.html
Added search function, is in fact, limited by the api itself.
> added search function

- assets/css/stlye.css
- index.html
Created lists for each recommended spec
> added list items for each recommended spec, added css and tailwind

- assets/javascript/script.js
> trying to fix api keys

- assets/css/stlye.css
- index.html
added and modified css and html
> added css and modified html

- assets/css/stlye.css
- index.html
Added TailWind to HTML, Deleted CSS styling
> added TailWind Styling

- assets/javascript/script.js
> fixed search function

- index.html
Added specs lists to HTML columns
> added spec lists for html columns

- assets/javascript/script.js
> clears arrays from previous searches

- assets/javascript/script.js
Added placeholders for when the arrays are available to display.
> added placeholder innerHTMLs

- index.html
> added a footer to HTML

- assets/javascript/script.js
> changed apikey

- assets/css/stlye.css
- index.html
Added background, different fonts, adjusted tailwind styling, added HTML comments
> added background, changed TailWind styling, added comments to HTML

- index.html
Added hover animations and url links to HTML
> added animation and links to HTML

- assets/javascript/script.js
Added ability to display basic min recommendation, still needs some work.
> added ability to display basic min recommendation

- assets/css/stlye.css
- index.html
changed color of the list tags
> changed color of the list tags

- index.html
> changed the title wording

- index.html
> fixed spelling errors
